# The base URL for the site.
baseURL = 'https://www.rowanars.net/'
# The title of the site.
title = 'Rowan Amateur Radio Society'
# Enable Git info â€º https://gohugo.io/methods/page/gitinfo/
enableGitInfo = false
# The default content language.
defaultContentLanguage = "en"
# Whether the default content language is in a subdirectory.
defaultContentLanguageInSubdir = false
# Whether the site has CJK language (Chinese, Japanese, Korean).
hasCJKLanguage = false

# Pagination settings.
[pagination]
  pagerSize = 5

# Make sure to include JSON output to support the search functionality.
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

# Sitemap configuration
[sitemap]
  changeFreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Disable other languages (only English)
disableLanguages = ["zh-cn", "zh-CN"]

# Import the theme.
[module]
  [[module.imports]]
    path = "github.com/geekifan/hugo-theme-chirpy"
    # Disable importing content from the theme's example site
    disableContent = true