# boolean type, the global switch for TOC in posts.
toc = true
# the avatar on sidebar, should be a relative path to /assets.
avatar = "img/commons/rars_logo.png"
author = "ai2f"

[assets]
  # Self-hosted static assets, default to false. If true, the assets will be hosted on your own server.
  self_host = false

[social]
  name = "Rowan Amateur Radio Society"
  url = "https://gettinhammered.com"

[[social.links]]
  type = "email"
  id = "rustyutahn@yahoo.com"
  icon = "fas fa-envelope"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
  noblank = true  # will not open in new window

[comments]
# Global switch for the post-comment system. [true | false]
enable = false
# The provider options are as follows: [disqus | utterances | giscus]
provider = ""

# Disqus options
[comments.disqus]
shortname = ""

# utterances settings › https://utteranc.es/
[comments.utterances]
repo = ""
issue_term = ""

# Giscus options › https://giscus.app
[comments.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = ""
strict = ""
input_position = ""
lang = ""
reactions_enabled = ""
